# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6152468f6577677b6a0981207c39c327bf31f74c73fd112a8682895d2fe5e81ceea77265548190cca79f76ade800619f4f5c0604786b8534af60a8f597aa32d

test:
  secret_key_base: 1979ed142b3284e3fc5c7d8728a69d93dec19c4f08f65d8e176317c4776ca52bd9d4d29f4dcf0854106927b9942ebba1a6b24c02d31717dd7f1e5c32e62d207d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
